---
apiVersion: v1
kind: Service
metadata:
  name: e-commerce
spec:
  type: NodePort
  selector:
    app: e-commerce-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000

---
# e-commerce svc
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce-svc
  template:
    metadata:
      labels:
        app: e-commerce-svc
    spec:
      containers:
        - name: e-commerce-svc
          image: public.ecr.aws/aws-gcr-solutions/centralized-logging-with-opensearch-workshop/e-commerce:v1.1.0
          env:
          - name: CL_WORKSHOP_DB_SECRET_NAME
            value: "$CL_WORKSHOP_DB_SECRET_NAME"
          - name: CL_REGION
            value: "$CL_REGION" # if you need to test by kubectl, you have to replace this value, this is for CDK deploy
          - name: CL_CLOUDFRONT_DOMAIN_NAME
            value: "$CL_CLOUDFRONT_DOMAIN_NAME"
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 4000
              protocol: TCP