---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# e-commerce svc
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-svc
  template:
    metadata:
      labels:
        app: nginx-svc
    spec:
      containers:
        - name: nginx-svc
          image: public.ecr.aws/aws-gcr-solutions/centralized-logging-with-opensearch-workshop/nginx:v1.1.0
          env:
          - name: CL_WORKSHOP_DB_SECRET_NAME
            value: "$CL_WORKSHOP_DB_SECRET_NAME"
          - name: CL_REGION
            value: "$CL_REGION" # if you need to test by kubectl, you have to replace this value, this is for CDK deploy
          - name: CL_CLOUDFRONT_DOMAIN_NAME
            value: "$CL_CLOUDFRONT_DOMAIN_NAME"
          - name: CL_LOG_GENERATOR_URL
            value: "$CL_LOG_GENERATOR_URL"
          resources:
            limits:
              cpu: 500m
              memory: 2048Mi
          ports:
            - containerPort: 80
              protocol: TCP